### ISSUE TITLE
Druid Workover

### ISSUE THREAD

**Issue by Nowayouthere** [impossible-bosses/impossible-bosses-public#20]
Enable Virtue in all Forms.
Move Bird Form from Staff to Class default
Bird Form: Transform Button, expire removed
Modify Vera Ability: 
Instead of 6 orbs/90sec make the ability charged: gains 1 orb every 10-15sec, maximum up to 6.
Make orbs instead be used as healing (distribute 225 to allies in target area)
tune down dmg, remove shred?
Add Single Target revive?: Cocoon, 30sec cd, forms a planty bulb around the corpse that automatically brings an ally to live with 50%hp and mana after 15sec. (dont need to channel)

**Comment by jmrico01** [comment]
## Vera - icon options

1. https://www.hiveworkshop.com/threads/inner-focus.328706/
![102128066-51a8fb00-3e1b-11eb-8689-0042d869159f](https://user-images.githubusercontent.com/11249051/102128448-e3186d00-3e1b-11eb-8b72-d8f1f8bd835f.png)
![veravera](https://user-images.githubusercontent.com/11249051/102128968-a436e700-3e1c-11eb-9259-703e15fb2a44.png)
1. https://www.hiveworkshop.com/resources/btnnaturesburst.92127/
![image](https://user-images.githubusercontent.com/11249051/102127826-fb3bbc80-3e1a-11eb-9579-8e7aa8ac792f.png)
1. https://www.hiveworkshop.com/resources/btnnaturebarriersphere.63180/
![image](https://user-images.githubusercontent.com/11249051/102127735-de06ee00-3e1a-11eb-99f9-a3962db099f7.png) 
1. https://www.hiveworkshop.com/resources/btnplaguenova.58680/
![image](https://user-images.githubusercontent.com/11249051/102127842-01319d80-3e1b-11eb-8699-c44e912f72cc.png)
1. https://www.hiveworkshop.com/resources/btnpoisonblast.58470/
![image](https://user-images.githubusercontent.com/11249051/102127854-068ee800-3e1b-11eb-8f98-c631af027cdb.png)
1. Orb of Venom (vanilla), current icon
![image](https://user-images.githubusercontent.com/11249051/102129082-d1839500-3e1c-11eb-8f3e-26febf6c6f97.png)
