### ISSUE TITLE
Various v1.11 bugs/notes

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#47]
### v1.11.0
- [x] Druid Q doesn't apply heal over time on bird form
- [x] Druid bird form is wayy too fast
- [x] Vera mana cost?
- [x] Counter has 8 second CD
- [x] Reconsider Sword: Radiance changes for DK, druid, priest EDIT reverted!
- [x] Tome: Shield tooltip says it's a weapon, not armor
- [x] Spells not working with classic hotkeys:
  - [x] DK shadow step
  - [x] Paladin heal, righteous strike, taunt
- [x] Clean up `ABI_ID_ITEM_STAFFNATURE`
- [x] I suspect there will be some lag on boss death, because of MMD stat publishing. Delay this a bit, and/or space it out more.
- [ ] Remove color code from player name? For MMD events and stuff.
- [x] Can probably disable MMD anti-tamper ticks, seems to be causing some lag.
- [ ] Noway's name had no class in the parenthesis.
- [x] Warrior Spirit re-triggering for classic hotkeys & cost 300 mana. Need 300+ mana for this to work/bug.

### v1.11.1
- [x] DK W doesn't track in hlrcvd
- [x] Staff: Nature tooltip has incorrect recharge time info.
- [x] Items can be sold: Super HP, savior, fallen remedy
- [x] Demonic Nether weird, maybe revert or just triple check
- [x] Skeletons can't counter
- [x] Hero Count on boss loot shop
- [x] LAG ?!? maybe?

### v1.11.2
- [x] Coins not spawning (!!!) (tested, HCL only)
- [x] DK Defile not killing ice blocks
- [x] DK Shadow Step hotkey? idk...
- [x] Report boss rank MMD, if it's not too much work
- [x] Ice Armor icon moves when autocast is enabled
- [x] L A G. check for memory leaks
- [x] Vera partial recharge display doesn't work in Reforged 1.32
- [x] Druid bird doesn't have a corpse, and can't deny

### v1.11.4
- [x] Random Powerup can be dropped and is missing standard tooltip warning. Essence also missing tooltip warning.
- [x] Scrolls, Powerup, and boss loot items can be traded! RIP
- [x] Token can't be bought again after repick. Token status is probably not reset, but the buff isn't reapplied.
- [x] Special effects aren't visible on druid bird form (rejuv, thunder boss recoil, etc)
- [x] Hero count item in hero select is broken
- [x] Random unique wasn't random unique... oh, it's based on the hero count item, so directly related to the above point.
- [x] Radiance tooltip has incorrect mana amount
- [x] Hotkey selection dialog - consider adding a repick option, or swapping order for nobnet map, or both
- [x] FM mana aura not working
- [x] Make tooltips on basic pot shop nicer. Too much random green text...

### v1.11.5
- [x] `Logging boss death` message...
- [x] Ob/Inf retaliate message overlaps with damage, hard to see
- [x] MMD stats sometimes disappear, and aren't well prioritized for endgame (e.g. player win/lose flags should always be first).
- [x] Spectators can't see first lobby (hotkey dialog fade is selective)
- [x] Rogue no-mana karma message wasn't displaying
- [x] Fix demonic victory+wipe scenario?
- [x] Vitality turned into Hope on demonic boss
- [x] Paladin Sanctuary Aura visible in class selection

### v1.11.6
- [x] Warrior stomp can trigger twice (2x damage and mana). Hotkey abilities issue.
- [x] Timeout force pick doesn't trim hotkey abilities.
- [ ] I think Easy wins don't record the Ancient boss kill, because it happens halfway.
- [ ] Player name colors previously showed up in chat, even in reforged, but I removed them for MMD, so now it's plain looking.
- [ ] MMD overall deaths not published correctly - it publishes the current deaths instead. Maybe get rid of all overall stats anyway...
- [ ] Make Tome: Shield a weapon again.
- [x] Martyr is always doing the extra damage (above 0.8% HP, lol...)

**Comment by Nowayouthere** [comment]
- [x] multiboard 2nd row of class icons don't update

**Comment by Nowayouthere** [comment]
- [x] DK still doesnt have to pay life when using Reanimate on nothing.
- [x] Multiboard bugs out after 3 boss selection

**Comment by Nowayouthere** [comment]
coin spawning disabled
dk defile does not kill iceblocks anymore (prolly dependent on check with bug ifix dummy unit)
