### ISSUE TITLE
Died with essence, didn't revive

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#54]
**Describe the bug**
Priest died with essence in inventory and didn't revive. He was revived with Exo a bit later and still had the essence.

I was able to replicate this bug. It can happen to any class, and it's related to a pathing issue at the start of the boss fight. On Thunder boss, right after you spawn, your pathing/collision seems to be disabled for a few seconds. This might happen for all boss fights just to make it easier for people to move out at the beginning, not sure. However, since Thunder boss's arena has cliffs, you can immediately walk into one of them like this:
![s](https://user-images.githubusercontent.com/11249051/111913595-43373480-8a45-11eb-8d2e-941a47f441c4.png)

If the boss kills you here (like I'm about to be run over in the screenshot), you'll be in non-pathable terrain, which I suspect makes the ankh item effect not work.

**Replay & Time**
~17:20 priest also gets stuck in terrain, dies close to 18:00, doesn't rez
[died-with-essence.zip](https://github.com/impossible-bosses/impossible-bosses-public/files/6168773/died-with-essence.zip)

**Comment by typical-methods** [comment]
That's really neat and would explain why sproket was able to leave the area at the start of the fight vs ancient, and got stuck outside the arena.

**Comment by jmrico01** [comment]
I'm just gonna call this a quirk of IB and not fix it, because it's probably always been like this. If you know, you know. Just don't go into any cliffs at the start of a fight.
