### ISSUE TITLE
Very Easy - infinite revives idea

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#58]
Based on a suggestion by typical_methods.

On Very Easy difficulty, for the first 4 bosses, if you die after you've used up all your Essences, you'll be automatically revived after some time (say 20 seconds). To keep things a bit in check, there should be a time limit for killing each boss (say 5 minutes).

This would split Very Easy difficulty into a "Beginner" mode on the first half of the bosses and a real mode with the usual perma-death on the latter half. This way noobs don't get discouraged after the inevitable one-shots during the first 4 bosses.

**Comment by typical-methods** [comment]
I've changed my mind on the scope of the idea. Just for the first boss or the first two bosses, and it would be made abundantly clear that Practice Time or Warm-up is over.
