### ISSUE TITLE
Display # of denies / armor level on Demonic

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#62]
There is currently no visual indication that denies lower the boss's armor. This is 1) unclear to people new to the fight, and 2) inconvenient for people who know the fight if they want to check the current boss armor level. They have to click on the boss mid-fight, and even then, the buff takes a little bit to update.

Without being too intrusive, we should display the boss's current armor level, at least when a deny happens.

**Comment by Nowayouthere** [comment]
implemented
