### ISSUE TITLE
druid HoT during light ult? people are angry? success?

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#75]
**Describe the bug**
lol, maybe disable this. all other HoTs aren't reflected during light ult.

OR EVERYTHING REFLECTS? EXTREME TROLL MODE??? hah, thinking about it...

**Replay & Time**

**Comment by Nowayouthere** [comment]
I think any healing associeted with a "Light" aspect should definitly reflect. So works as intended?

Close this?
